### PR TITLE
[WIP] Add assertions.lib and files.op

### PR DESCRIPTION
**Pull request by MalloZup**
### What does this PR do?

Add some work-in-progress.

Add files.py library. One good function for avoid complex sed,  instead use python.
Thinking Open-question how to execute this function in multi-machine context.
### What issues does this PR fix or reference (if it fix any issues) ?

None
### Previous Behavior ( if applicable)

No functions for test-library
### New Behavior (if applicable)

Add some functions for test-api
### Tests written? ( unit-test for new-feature/PR, units-test for susetest_api, etc. )

No test for moment.

### CODE REVIEW

**Comment by MalloZup** [comment]
I think the best solution for replace_string(node, dictonary string, filename) is to:

###prototype elegant way ! 

```
data_from file= node.run(cat filename))
..
data_from file = do string replacemets
...
#write the new buf to file.
node.run(echo "{}".format(data_from_file))
```

this should work fine without any complication.

**Comment by MalloZup** [comment]
@okirch :wow, i can call node.journal.info that's cool.

@okirch  do you know what is the purpose/diffrence from receivefile and recvbuffer? 
i want to copy to a var the content from a file, as an example from server.

```
data_from file= node.run(cat filename))
i think here should be used recvfile or recvbuffer
```

**Comment by okirch** [comment]
Hi Dario,

On Tue, 2016-05-17 at 12:41 -0700, Dario Maiocchi wrote:

> @okirch do you know what is the purpose/diffrence from receivefile and
> recvbuffer? 
> i want to copy to a var the content from a file, as an example from
> server.

The *buffer functions should probably be documented in some manpages;
unfortunately they aren't right now.

recvfile/sendfile:
    these functions transfer a file from the SUT to a file on
    the control node, or vice versa.

```
This is useful, for instance, if you need to copy a
tarball to the SUT and unpack it there.
```

recvbuffer/sendbuffer
    these functions transfer a file from the SUT to a
    python bytearray object, or vice versa.

```
This is useful if you want to process the content
of a file on the SUT (eg add an entry to /etc/hosts)
```

> data_from file= node.run(cat filename))
> i think here should be used recvfile or recvbuffer

Correct. Note that the returned object will be a bytearray object, so in
order to do string processing on it you need to convert it first:

```
data = node.recvbuffer("/some/file")
if not data:
    bla bla error

strdata = str(data)
```

Similarly, if you want to upload string data, you need to convert it to
a bytearray first:

```
user = "dario"
welcome = "Welcome to %s's Linux box" % user
if not node.sendbuffer("/etc/motd", bytearray(welcome)):
    bla bla error
```

Hope this helps!

Regards,
Olaf

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

## 

Olaf Kirch - Director SUSE Linux Enterprise; R&D (okir@suse.com)
SUSE Linux GmbH, Maxfeldstr. 5, 90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Dilip Upmanyu, Graham Norton,
HRB 21284 (AG Nürnberg)

**Comment by MalloZup** [comment]
Hi Olaf, 
thx  this helps ! :+1:

**Pull request merged**
